# https://docs.travis-ci.com/user/languages/java/
language: java
sudo: false
jdk:
  - oraclejdk8
install:
  - curl -s https://get.sdkman.io | bash
  - source $HOME/.sdkman/bin/sdkman-init.sh
  - sdk install kotlin
  - gradle assemble
script:
  - kotlinc -script test.kts -classpath build/classes/main
